name: Testing
on:
  push:
    branches:
      - develop
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: setup
        run: npm ci
      - name: test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
